verturin_groupemailer_read:
    path: /gm/{token}
    defaults: { _controller: verturin.groupemailer.controller.confirm:handle }
    requirements:
        token: '[A-Za-z0-9]+'

verturin_groupemailer_unsubscribe:
    path: /gmu/{token}
    defaults: { _controller: verturin.groupemailer.controller.confirm:unsubscribe }
    requirements:
        token: '[A-Za-z0-9]+'

verturin_groupemailer_resubscribe:
    path: /gmr/{token}
    defaults: { _controller: verturin.groupemailer.controller.confirm:resubscribe }
    requirements:
        token: '[A-Za-z0-9]+'

verturin_groupemailer_confirm:
    path: /groupemailer/confirm/{token}
    defaults: { _controller: verturin.groupemailer.controller.confirm:handle }
    requirements:
        token: '[A-Za-z0-9]+'
